#!/usr/bin/env node
// Strictly read-only: only Supabase select() is used.
import { createClient } from '@supabase/supabase-js';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const names=['Caminhões','Constellation','Delivery','Explorer','Ecosport','Fiesta','Ranger','Passat','Santana','Saveiro','Voyage','Parati','Amarok','Kombi','Corsa','Meriva','Montana','Celta','Palio','Siena','Strada','Gol','Fox','Polo','Titan','Tractor','Worker','F-150'];
const vr=new RegExp('\\b(?:'+names.map(x=>x.replace('-','\\-')).join('|')+')\\b','i'), pr=/\b(\d{2})\s*(?:a|à|-)\s*(\d{2})\b|\b(?:após|apos)\s+(\d{2})\b|\b(?:até|ate)\s+(\d{2})\b/i, dr=/\b(2P\s*\/\s*4P|2\s*\/\s*4\s*Portas|[2345]\s*(?:P\b|Portas?\b))/i;
const e={veiculo:'',geracao:'',ano_apos:'',ate:'',portas:'',obs:'',conversao:''}, n=x=>String(x??'').replace(/\s+/g,' ').trim(), f=x=>({...e,...Object.fromEntries(Object.entries(x||{}).map(([k,v])=>[k,n(v)]))});
const per=s=>{let m=n(s).match(pr);return !m?{ano_apos:'',ate:''}:m[1]?{ano_apos:m[1],ate:m[2]}:m[3]?{ano_apos:m[3],ate:''}:{ano_apos:'',ate:m[4]}}, dor=s=>{let m=n(s).match(dr);return !m?'':/\//.test(m[1])?'2/4':m[1].match(/[2345]/)[0]};
function gen(s){let m=n(s).match(/\(?\s*(G(?:I|V|X)+(?:\s*(?:\/|\||a)\s*G(?:I|V|X)+)*)\s*\)?/i);let g=m?m[1].replace(/\s*\|\s*/g,'/').replace(/\s*\/\s*/g,'/').replace(/\s+a\s+/i,' a '):'';return g==='GII/GII/GIV'?'GII/GIII/GIV':g}
function clean(s){return n(s.replace(/\([^)]*\)/g,' ').replace(pr,' ').replace(dr,' ').replace(/\bG(?:I|V|X)+(?:\s*(?:\/|\||a)\s*G(?:I|V|X)+)*\b/gi,' ').replace(/\b(?:Gl|Dir|D\/E|Dianteira|Direita|Esquerda|Preta|Tras\.?|Diant)\b/gi,' ').replace(/^[,;:/\- ]+|[,;:/\- ]+$/g,''))}
export function parseApplications(d){let src=n(d),dashIx=src.lastIndexOf(' - '),dashBlock=dashIx>=0?src.slice(dashIx+3):'',ix=(dashIx>=0&&vr.test(dashBlock))?dashIx+3:(src.match(vr)?.index??src.length);let prefix=src.slice(0,ix),block=src.slice(ix),global=dor(prefix),split=new RegExp('\\s*/\\s*(?=(?:'+names.map(x=>x.replace('-','\\-')).join('|')+')\\b)','gi'),parts=block.split(split).map(n).filter(Boolean),tail=per(parts.at(-1)),ownPeriodCount=parts.filter(s=>{let pp=per(s);return pp.ano_apos||pp.ate}).length,apps=[];for(let s of parts){let p=per(s);if(!p.ano_apos&&!p.ate&&ownPeriodCount<=1&&(tail.ano_apos||tail.ate))p=tail;let doors=dor(s)||global,obs=/\(\s*Tras\.?\s*\)/i.test(s)?'Traseira':/\(\s*Diant\s*\/\s*Tras\s*\)/i.test(s)?'Dianteira/Traseira':'';if(/^Fiesta\s*\(/i.test(s)){for(let x of s.match(/\(([^)]+)\)/)[1].split('/'))apps.push(f({veiculo:n('Fiesta '+x.replace(/\bG(?:I|V|X)+\b/gi,'')),geracao:gen(x),...p,portas:doors,obs}));continue}let fm=s.match(/^F-(150)\|(250)\|(350)\|(4000)\b/i);if(fm){for(let x of fm.slice(1))apps.push(f({veiculo:'F-'+x,...p,portas:doors,obs}));continue}let v=clean(s);if(v)apps.push(f({veiculo:v,geracao:gen(s),...p,portas:doors,obs}));}return{applications:apps,ambiguous:!apps.length,reasons:apps.length?[]:['bloco de aplicações não identificado']}}
const can=a=>(a||[]).map(f).map(x=>Object.fromEntries(Object.keys(e).map(k=>[k,x[k]]))),eq=(a,b)=>JSON.stringify(can(a))===JSON.stringify(can(b)),key=a=>[a.veiculo,a.geracao,a.ano_apos,a.ate,a.portas,a.obs].map(x=>n(x).toLowerCase()).join('|');
export function preserveConversions(p,c){let m=new Map(can(c).filter(x=>x.conversao).map(x=>[key(x),x.conversao]));return can(p).map(x=>({...x,conversao:m.get(key(x))||''}))}
async function load(c){let a=[];for(let i=0;;i+=1000){let{data,error}=await c.from('produtos').select('codigo,descricao,aplicacoes').eq('ativo',true).order('codigo').range(i,i+999);if(error)throw error;a.push(...data);if(data.length<1000)return a}}
const R={'1004':[['Passat LS','','','94','3'],['Gol','','','94',''],['Voyage','','','94','']],'1013':[['Caminhões','','','',''],['Gol','','87','94',''],['Passat','','','79',''],['Santana','','85','89','']],'1139':[['Gol','GV','08','12',''],['Gol','GVI','12','15',''],['Gol','GVII','16','','']],'1149':[['Saveiro','GII/GIII/GIV','97','08','']],'1174':[['Gol','GII/GIII/GIV','94','14',''],['Parati','GII/GIII/GIV','96','12',''],['Saveiro','GII/GIII/GIV','97','12','']],'1176':[['Gol','GII/GIII','','','4']],'12119':[['Saveiro','GV','09','10',''],['Amarok','','10','','']],'12137':[['Constellation','','','',''],['Delivery','','96','17',''],['Fox','GI','03','09',''],['Gol','GII a GVI','94','15',''],['Kombi Clipper','','07','12',''],['Parati','GII a GIV','96','12',''],['Polo','GII','02','09',''],['Saveiro','GII a GV','97','13',''],['Titan','','96','17',''],['Tractor','','96','17',''],['Worker','','96','17','']],'12148':[['Saveiro','GII/GIII/GIV','','','']],'2036':[['Explorer','','96','99',''],['F-150','','99','',''],['F-250','','99','',''],['F-350','','99','',''],['F-4000','','99','',''],['Ranger','GI','98','12','']],'2101':[['Ecosport','GI','03','12','','Traseira'],['Fiesta Amazon','','02','14','','Traseira'],['Fiesta Hatch','GII','02','14','','Traseira'],['Fiesta Sedan','GII','02','14','','Traseira'],['Ranger','GII','09','12','','Dianteira/Traseira']],'30202':[['Corsa Hatch','GII','02','12',''],['Meriva','','02','12',''],['Montana','','03','10','']],'30242':[['Corsa Hatch','GII','02','12',''],['Meriva','','03','12','']],'3054':[['Celta','','03','06','2']],'3056':[['Celta','','03','06','4']],'3068':[['Celta','','01','06','2/4']],'4052':[['Palio','','','04','2/4']],'4222':[['Palio','','','03','2/4'],['Siena','','','03','2/4'],['Strada','','','03','2/4']]};
const want=r=>r.map(([veiculo,geracao,ano_apos,ate,portas,obs])=>f({veiculo,geracao,ano_apos,ate,portas,obs}));
async function main(){let url=process.env.VITE_SUPABASE_URL,k=process.env.VITE_SUPABASE_ANON_KEY;if(!url||!k)throw Error('Defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY.');let all=await load(createClient(url,k,{auth:{persistSession:false,autoRefreshToken:false}})),tests=Object.entries(R).map(([codigo,x])=>{let p=all.find(q=>String(q.codigo)===codigo),actual=p?parseApplications(p.descricao).applications:[];return{codigo,passed:!!p&&eq(actual,want(x)),expected:want(x),actual}}),bad=tests.filter(x=>!x.passed);if(bad.length){console.error(JSON.stringify({reference_tests:{total:tests.length,passed:tests.length-bad.length,failed:bad.length},failed:bad.map(x=>x.codigo)},null,2));process.exitCode=1;return}let report=all.map(p=>{let z=parseApplications(p.descricao),q=preserveConversions(z.applications,p.aplicacoes);return{codigo:p.codigo,descricao:p.descricao,aplicacoes_atuais:can(p.aplicacoes),aplicacoes_propostas:q,status:z.ambiguous?'ambiguous':eq(q,p.aplicacoes)?'unchanged':'changed',ambiguidades:z.reasons}}),summary={total:report.length,unchanged:report.filter(x=>x.status==='unchanged').length,changed:report.filter(x=>x.status==='changed').length,ambiguous:report.filter(x=>x.status==='ambiguous').length,reference_tests:{total:tests.length,passed:tests.length,failed:0}},dir=path.resolve('reports');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'rebuild-aplicacoes-dry-run.json'),JSON.stringify({summary,reference_tests:tests,products:report},null,2));console.log(JSON.stringify(summary,null,2))}
if(process.argv[1]&&import.meta.url.endsWith(process.argv[1].replace(/\\/g,'/')))main().catch(x=>{console.error(x);process.exitCode=1});
